---

- name: Create the OSP data directory
  file:
    path: /osp
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Create the OSP config directory
  file:
    path: /etc/osp
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Apply the OSP configs
  template:
    src: '{{ item }}.yml.j2'
    dest: /etc/osp/{{ item }}.yml
  with_items:
    - osp
    - osp.test

- name: Configure .profile
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/.profile
    line: '{{ item }}'
  with_items: osp_profile
