---

- name: Update the OSP source code
  git:
    repo: '{{ osp_repo }}'
    version: '{{ osp_branch }}'
    dest: '{{ osp_src }}'

- name: Set source code permissions
  file:
    path: '{{ osp_src }}'
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    recurse: yes

- name: Check if a virtualenv exists
  register: env
  stat:
    path: '{{ osp_src }}/env'

# pyvenv is broken on Ubuntu 14.04.
- name: Create a Python 3 virtualenv, if necessary
  when: env.stat.isdir is not defined
  command: virtualenv --python=/usr/bin/python3.4 env
  args:
    chdir: '{{ osp_src }}'

- name: Install pip dependencies
  command: env/bin/pip3 install -r requirements.txt
  args:
    chdir: '{{ osp_src }}'

- name: Install the CLI suite
  command: env/bin/python3 setup.py develop
  args:
    chdir: '{{ osp_src }}'

- name: Create OSP tables
  when: osp_init_db
  command: env/bin/osp {{ item }} init_db
  with_items: osp_db_modules
  args:
    chdir: '{{ osp_src }}'
