---

- name: Install dependencies
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - python-virtualenv
    - python3-setuptools
    - python3-dev
    - libpq-dev
    - libxslt1-dev
    - libxml2-dev
    - libreoffice

- name: Configure .profile
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/.profile
    line: '{{ item }}'
  with_items: osp_profile

- name: Create the OSP config directory
  file:
    path: /etc/osp
    state: directory

- name: Apply the OSP config
  template:
    src: osp/osp.yml.j2
    dest: /etc/osp/osp.yml
