---

- name: Configure OSP workers
  sudo: yes
  hosts:
    - tag_osp_server
    - tag_osp_worker

  vars_files:
    - vars/osp.yml
    - vars/elasticsearch.yml
    - vars/postgres.yml
    - vars/local.yml

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
    - nginx
    - workers
