---

- name: Provision a worker set
  hosts: localhost

  tasks:

    - name: Start the data repository
      register: servers
      ec2:

        image: '{{ ec2_image }}'
        keypair: '{{ ec2_keypair }}'
        group: '{{ ec2_group }}'
        region: '{{ ec2_region }}'

        instance_type: '{{ ec2_server_instance_type }}'
        vpc_subnet_id: '{{ ec2_subnet_id }}'

        assign_public_ip: yes
        wait: yes

        volumes:
          - device_name: /dev/sda1
            volume_size: '{{ ec2_server_volume_size }}'

        exact_count: '{{ ec2_server_count }}'

        instance_tags:
          Name: osp-server
          Environment: osp-server
          osp: server

        count_tag:
          osp: server

    - name: Start the workers
      register: workers
      ec2:

        image: '{{ ec2_image }}'
        keypair: '{{ ec2_keypair }}'
        group: '{{ ec2_group }}'
        region: '{{ ec2_region }}'

        instance_type: '{{ ec2_worker_instance_type }}'
        vpc_subnet_id: '{{ ec2_subnet_id }}'

        assign_public_ip: yes
        wait: yes

        exact_count: '{{ ec2_worker_count }}'

        instance_tags:
          Name: osp-worker
          Environment: osp-worker
          osp: worker

        count_tag:
          osp: worker

    - name: Attach the OSP volume
      ec2_vol:

        instance: '{{ item.id }}'
        snapshot: '{{ ec2_osp_snapshot }}'
        region: '{{ ec2_region }}'
        volume_size: 1 # Ansible bug-fix.

      with_flattened:
        - workers.instances
        - servers.instances
