---

- name: Install generic dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - git

- name: Mount the OSP volume
  ignore_errors: yes
  mount:
    fstype: ext4
    src: /dev/xvdf
    name: /osp
    state: mounted
