---

osp_repo: https://github.com/overview/osp.git
osp_branch: master
osp_src: /home/{{ ansible_ssh_user }}/osp
osp_uwsgi_config: /etc/uwsgi
osp_numprocs: 4
osp_data_host: localhost
osp_init_db: yes

osp_profile:
  - . osp/env/bin/activate

osp_db_modules:
  - corpus
  - hlom

tika_download_url: http://mirrors.sonic.net/apache/tika/tika-server-1.7.jar
tika_path: /etc/tika
tika_jar: tika-server-1.7.jar
