---

osp_repo: https://github.com/overview/osp.git
osp_branch: master
osp_src: /home/{{ ansible_ssh_user }}/osp
osp_numprocs: 4
osp_data_host: localhost
osp_init_db: yes

osp_profile:
  - . osp/env/bin/activate

osp_db_modules:
  - corpus
  - hlom
  - dates
  - institutions
  - locations
