---

- name: Add the Orace Java PPA
  apt_repository:
    repo: ppa:webupd8team/java
    update_cache: yes

- name: Accept the Oracle license
  shell: >
    echo debconf shared/accepted-oracle-license-v1-1 select true |
    sudo debconf-set-selections

- name: Install Oracle Java
  apt:
    pkg: oracle-java7-installer
    state: latest
    update_cache: yes

- name: Download the Debian package
  get_url:
    url: '{{ es_url }}/elasticsearch-{{ es_version }}.deb'
    dest: /tmp/elasticsearch-{{ es_version }}.deb
    mode: 0440

- name: Install the package
  shell: dpkg -i /tmp/elasticsearch-{{ es_version }}.deb

- name: Apply the configuration
  notify: restart elasticsearch
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    mode: 0644
