---

- name: Add the Orace Java PPA
  apt_repository:
    repo: ppa:webupd8team/java
    update_cache: yes

- name: Accept the Oracle license
  shell: >
    echo debconf shared/accepted-oracle-license-v1-1 select true |
    sudo debconf-set-selections

- name: Install Oracle Java
  apt:
    pkg: oracle-java7-installer
    state: latest
    update_cache: yes
