---

ec2_region: '{{ lookup("env", "OSP_REGION") }}'
ec2_subnet_id: '{{ lookup("env", "OSP_SUBNET_ID") }}'
ec2_keypair: '{{ lookup("env", "OSP_KEYPAIR") }}'
ec2_osp_snapshot: '{{ lookup("env", "OSP_CORPUS_SNAPSHOT") }}'
ec2_image: ami-9eaa1cf6

ec2_server_instance_type: t2.small
ec2_server_count: 1

ec2_worker_instance_type: t2.small
ec2_worker_count: 0
