---

ec2_region: us-east-1
ec2_image: ami-9eaa1cf6

ec2_server_instance_type: c4.4xlarge
ec2_server_count: 0

ec2_worker_instance_type: c4.4xlarge
ec2_worker_count: 0

ec2_render_instance_type: r3.4xlarge
ec2_render_count: 1
ec2_render_volume_size: 1000
