---

# *** Vagrant ***

# Local path for synced OSP code.
osp_sync_code: XXX

# Local path for synced OSP data.
osp_sync_data: XXX

# *** EC2 ***

# VPC subnet to house the instances.
ec2_subnet_id: subnet-XXX

# AWS keypair to use when creating instances.
ec2_keypair: XXX

# ID of the OSP EBS snapshot.
ec2_osp_snapshot: snap-XXX

# A user-specific EC2 instance tag.
ec2_namespace: XXX

# IP address of the central data server.
osp_data_host: XXX

# Other local overrides:
# ...
